obstacle_range: 2.5
raytrace_range: 3
footprint: [[0.2,-0.1], [-0.2, -0.1], [-0.2, 0.1], [0.2, 0.1]] # centered at (0,0,0)
inflation_radius: 0.2 #0.55 # max distance from obstacles at which cost should be incurred - all paths that keep obsticles this mcuh away will have equal cost

robot_base_frame: base_footprint

observation_sources: laser_scan_sensor

laser_scan_sensor: {sensor_frame: lidar, data_type: LaserScan, topic: scan, marking: true, clearing: false} # marking and clearing allow the sensor to add or remove obsticleinformation from the costmap

