obstacle_range: 2.5
raytrace_range: 3
footprint: [[.2,-.1], [-.2, -.1], [-.2, .1], [.2, .1]] # centered at (0,0,0)
inflaction_radius: 0.55 # max distance from obstacles at which cost should be incurred - all paths that keep obsticles this mcuh away will have equal cost

observation_sources: laser_scan_sensor

laser_scan_sensor: {sensor_frame: lidar, data_type: LaserScan, topic: scan, marking: true, clearing:true} # marking and clearing allow the sensor to add or remove obsticleinformation from the costmap

