global_costmap:
  global_frame: map
  rolling_window: false
  track_unknown_space: true
  update_frequency: 2.0
  publish_frequency: 1.0
  static_map: true
  resolution: 0.10
  plugins:
    - name: static_map
      type: "costmap_2d::StaticLayer"
    - name: obstacle_layer
      type: "costmap_2d::ObstacleLayer"
    - name: footprint_layer
      type: "costmap_2d::FootprintLayer"
    - name: inflation_layer
      type: "costmap_2d::InflationLayer"
