local_costmap:
  global_frame: map
  robot_base_frame: base_footprint
  update_frequency: 5.0
  publish_frequency: 2.0 # rate this will publish visual info
  static_map: false
  rolling_window: true # costmap will remain centered on robot
  width: 6.0
  height: 6.0
  resolution: 0.05 # meters/cell

# see wiki.ros.org/costmap_2d for more info
